// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {formulaHighlighting} from "./highlights"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UOVQPOOOnQPO'#CcQsQPOOOVQPO'#CuOOQO'#Cz'#CzO!kQPO,58}OVQPO,59SOVQPO,59SOVQPO,59SOVQPO,59SO!rQPO,59aOOQO1G.i1G.iO!yQPO1G.iO$OQPO1G.nO$YQPO1G.nO%RQPO1G.nO%iQPO1G.nOOQO1G.{1G.{OVQPO'#CvO&PQPO7+$TOOQO7+$T7+$TO&XQPO,59bOOQO-E6t-E6tOOQO<<Go<<Go",
  stateData: "&i~OmOS~OQSORSOSSOTSOUSOWPOXRO~OXTO~O]UO^UO_VO`VOaVObWOcWOdWOeWOfWOgWOhXO~OZZO~PVOZaO~PsOYbOZdO~PsOaVO][i^[ib[ic[id[ie[if[ig[ih[ik[iZ[iY[i~O_VO`VO~P#TO_[i`[i~P#TO]UO^UO_VO`VOaVOh[ik[iZ[iY[i~Ob[ic[id[ie[if[ig[i~P$dObWOcWOdWOeWOfWOgWO~P$dOYbOZgO~OYjaZja~PsOTSUWU~",
  goto: "!joPPPPPPPpPPPPpPPPPPPPPPPPPpzPPP!QaSORTUVWXbQc[RfcQQOQYRQ[TQ]UQ^VQ_WQ`XReb",
  nodeNames: "⚠ Expression Number String Boolean CellRange CellReference FunctionCall Function ( , ) BinaryExpression + - * / ^ = > < >= <= <> & ParenExpression",
  maxTerm: 30,
  propSources: [formulaHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "+e~RmX^!|pq!|rs#qvw%_xy%dyz%iz{%n{|%s|}%x}!O%}!P!Q&S!Q![&X!^!_&r!_!`'X!`!a'^!c!h'k!h!i(z!i!v'k!v!w*l!w!}'k#Q#R+`#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~#RYm~X^!|pq!|#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~#tVOr#qrs$Zs#O#q#O#P$`#P;'S#q;'S;=`%X<%lO#q~$`OR~~$cRO;'S#q;'S;=`$l;=`O#q~$oWOr#qrs$Zs#O#q#O#P$`#P;'S#q;'S;=`%X;=`<%l#q<%lO#q~%[P;=`<%l#q~%dOh~~%iOX~~%nOZ~~%sO_~~%xO]~~%}OY~~&SO^~~&XO`~~&^QQ~!O!P&d!Q![&X~&gP!Q![&j~&oPQ~!Q![&j~&wQd~!_!`&}!`!a'S~'SOf~~'XOg~~'^Ob~~'cPc~!_!`'f~'kOe~~'pQW~!Q!['v!c!}'k~'}RU~W~!Q!['v![!](W!c!}(o~(ZP!c!}(^~(aQ!Q![(g!c!}(^~(lPT~!Q![(g~(tQW~!Q![(o!c!}(o~)PRW~!Q!['v!c!d)Y!d!}'k~)_SW~!Q!['v!c!n'k!n!o)k!o!}'k~)pSW~!Q!['v!c!u'k!u!v)|!v!}'k~*RSW~!Q!['v!c!g'k!g!h*_!h!}'k~*fQS~W~!Q!['v!c!}'k~*qSW~!Q!['v!c!t'k!t!u*}!u!}'k~+SSW~!Q!['v!c!w'k!w!x)|!x!}'k~+eOa~",
  tokenizers: [0],
  topRules: {"Expression":[0,1]},
  tokenPrec: 249,
  termNames: {"0":"⚠","1":"@top","2":"Number","3":"String","4":"Boolean","5":"CellRange","6":"CellReference","7":"FunctionCall","8":"Function","9":"\"(\"","10":"\",\"","11":"\")\"","12":"BinaryExpression","13":"\"+\"","14":"\"-\"","15":"\"*\"","16":"\"/\"","17":"\"^\"","18":"\"=\"","19":"\">\"","20":"\"<\"","21":"\">=\"","22":"\"<=\"","23":"\"<>\"","24":"\"&\"","25":"ParenExpression","26":"(\",\" expression)+","27":"␄","28":"%mainskip","29":"whitespace","30":"expression"}
})
