// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Expression = 1,
  Number = 2,
  String = 3,
  Boolean = 4,
  CellRange = 5,
  CellReference = 6,
  FunctionCall = 7,
  Function = 8,
  BinaryExpression = 12,
  ParenExpression = 25
